ATM-app/Controllers/CheckingAccountController.cs
using ATM_app.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATM_app.Controllers
{
    public class CheckingAccountController : Controller
    {
        // GET: CheckingAccount
        public ActionResult Index()
        {
            return View();
        }

        // GET: CheckingAccount/Details
        public ActionResult Details()
        {
            var checkingAccount = new CheckingAccount { AccountNumber = "0000123456", FirstName = "Tor Andreas", LastName = "Johnsen", Balance = 1200 };
            return View(checkingAccount);
        }

        // GET: CheckingAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CheckingAccount/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: CheckingAccount/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CheckingAccount/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ATM-app/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ATM_app.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Any questions? Send us a message!";
            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            // TODO send message to HQ
            ViewBag.TheMessage = "Thanks, we got your message.";

            return View();
        }

        public ActionResult Blog()
        {
            ViewBag.Message = "Blog page.";

            return View();
        }

        public ActionResult Serial(string letterCase)
        {
            var serial = "ASPNETMVCATM1";
            if (letterCase == "lower")
            {
                return Content(serial.ToLower());
            }
            return Content(serial);
        }
    }
}

ATM-app/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ATM-app/Views/Home/Blog.cshtml
@{
    ViewBag.Title = "Blog";
}

<h2>@ViewBag.Title</h2>
<h2>@ViewBag.Message</h2>

ATM-app/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<h3>@ViewBag.TheMessage</h3>

<form method="POST">
    <textarea name="message"></textarea>
    <input type="submit" value="Send" />
</form>

ATM-app/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-circle-arrow-down"></span> Withdrawal</a>
        <a href="#" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-flash"></span> Quick Cash 100 kr</a>
        <a href="@Url.Action("Details", "CheckingAccount")" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-question-sign"></span> Balance Inquiry</a>
    </div>
    <div class="col-md-6 margin-top-20">
        <a href="#" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-print"></span> Print Statement</a>
        <a href="#" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-transfer"></span> Transfer Funds</a>
        <a href="#" class="btn btn-primary btn-block"><span class="glyphicon glyphicon-circle-arrow-up"></span> Deposit</a>
    </div>
</div>